USE [GD1C2020]
GO

-- Crea el esquema si no existe. Si ya existe, elimina todo y vuelve a crearlo.
IF EXISTS (SELECT SCHEMA_ID FROM sys.schemas WHERE [name] = 'GDD2020')
BEGIN
	PRINT('El Schema GDD2020. ya existe! Eliminando...')


--Eliminar Contraits
	PRINT('Eliminando constraints...')

	--Tabla rol Por Usuario
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].UC_ROLXUSUARIO')  )
	ALTER TABLE [GDD2020].[ROLXUSUARIO] DROP CONSTRAINT UC_ROLXUSUARIO
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_RXU_ROL_CODIGO')  )
	ALTER TABLE [GDD2020].[ROLXUSUARIO] DROP CONSTRAINT FK_RXU_ROL_CODIGO
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_RXU_USUARIO_USERNAME')  )
	ALTER TABLE [GDD2020].[ROLXUSUARIO] DROP CONSTRAINT FK_RXU_USUARIO_USERNAME

	--Tabla CLiente      Saquè la s porque la tabla en el der se llama cliente
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_CLIENTE_USUARIO_USERNAME')  )
	ALTER TABLE [GDD2020].[CLIENTE] DROP CONSTRAINT FK_CLIENTE_USUARIO_USERNAME

	
	--Tabla Rol x Funcionalidad --> VER DE CAMBIAR LOS NOMBRES
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].UC_ROL_X_FUNCIONALIDAD')  )
	ALTER TABLE [GDD2020].[FUNCIONALIDADXROL] DROP CONSTRAINT UC_ROL_X_FUNCIONALIDAD
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_RXF_ROL_CODIGO')  )
	ALTER TABLE [GDD2020].[FUNCIONALIDADXROL] DROP CONSTRAINT FK_RXF_ROL_CODIGO
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_RXF_FUNC_CODIGO')  )
	ALTER TABLE [GDD2020].[FUNCIONALIDADXROL] DROP CONSTRAINT FK_RXF_FUNC_CODIGO

	--Tabla Avion
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_AVION_BUTACA_NUMERO')  )
	ALTER TABLE [GDD2020].[AVION] DROP CONSTRAINT FK_AVION_BUTACA_NUMERO

 	--Tabla Vuelo
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_VUELO_AVION_IDENTIFICADOR')  )
	ALTER TABLE [GDD2020].[VUELO] DROP CONSTRAINT FK_VUELO_AVION_IDENTIFICADOR 
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_VUELO_RUTA_AEREA_CODIGO ')  )
	ALTER TABLE [GDD2020].[VUELO] DROP CONSTRAINT FK_VUELO_RUTA_AEREA_CODIGO 

--yo
	--Tabla Habitacion
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_TIPO_HABITACION_CODIGO')  )
	ALTER TABLE [GDD2020].[HABITACION] DROP CONSTRAINT FK_TIPO_HABITACION_CODIGO 

	--Tabla Hotel
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_HABITACION_NUMERO')  )
	ALTER TABLE [GDD2020].[HOTEL] DROP CONSTRAINT FK_HABITACION_NUMERO

	--Tabla Compra_Estadia
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_HOTEL_CODIGO')  )
	ALTER TABLE [GDD2020].[COMPRA_ESTADIA] DROP CONSTRAINT FK_HOTEL_CODIGO

	--Estadia por dia
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_FACTURA_NRO')  )
	ALTER TABLE [GDD2020].[ESTADIA_X_DIA] DROP CONSTRAINT FK_FACTURA_NRO 

	--Venta Estadia
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_FACTURA_NRO')  )
	ALTER TABLE [GDD2020].[VENTA_ESTADIA] DROP CONSTRAINT FK_FACTURA_NRO
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_FECHA_ESTADIA_CODIGO')  )
	ALTER TABLE [GDD2020].[VENTA_ESTADIA] DROP CONSTRAINT FK_FECHA_ESTADIA_CODIGO
	
	--Factura
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_NUMERO_CLIENTE')  )
	ALTER TABLE [GDD2020].[FACTURA] DROP CONSTRAINT FK_NUMERO_CLIENTE 
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_SUCURSAL_CODIGO')  )
	ALTER TABLE [GDD2020].[FACTURA] DROP CONSTRAINT FK_SUCURSAL_CODIGO 
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_COMPRA_NUMERO')  )
	ALTER TABLE [GDD2020].[FACTURA] DROP CONSTRAINT FK_COMPRA_NUMERO
	
	--Compra
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_PASAJE_CODIGO')  )
	ALTER TABLE [GDD2020].[COMPRA] DROP CONSTRAINT FK_PASAJE_CODIGO 
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_PROVEEDOR_CODIGO')  )
	ALTER TABLE [GDD2020].[COMPRA] DROP CONSTRAINT FK_PROVEEDOR_CODIGO 
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_ESTADIA_CODIGO')  )
	ALTER TABLE [GDD2020].[COMPRA] DROP CONSTRAINT FK_ESTADIA_CODIGO 
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_USUARIO_USERNAME')  )
	ALTER TABLE [GDD2020].[COMPRA] DROP CONSTRAINT FK_USUARIO_USERNAME   

	--Pasaje
	IF EXISTS (  SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[GDD2020].FK_VUELO_CODIGO')  )
	ALTER TABLE [GDD2020].[PASAJE] DROP CONSTRAINT FK_VUELO_CODIGO 
	

--Eliminar tablas
	PRINT('Eliminando tablas...')

	IF OBJECT_ID('[GDD2020].[SUCURSALES]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[SUCURSALES]

	IF OBJECT_ID('[GDD2020].[CLIENTE]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[CLIENTE]

	IF OBJECT_ID('[GDD2020].[PROVEEDOR]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[PROVEEDOR]

	IF OBJECT_ID('[GDD2020].[USUARIO]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[USUARIO]

	IF OBJECT_ID('[GDD2020].[ROLXUSUARIO]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[ROLXUSUARIO]

	IF OBJECT_ID('[GDD2020].[ROL]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[ROL]

	IF OBJECT_ID('[GDD2020].[FUNCIONALIDAD]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[FUNCIONALIDAD]

	IF OBJECT_ID('[GDD2020].[FUNCIONALIDADXROL]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[FUNCIONALIDADXROL]

	IF OBJECT_ID('[GDD2020].[TIPO_BUTACA]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[TIPO_BUTACA]

	IF OBJECT_ID('[GDD2020].[BUTACA]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[BUTACA]

	IF OBJECT_ID('[GDD2020].[AVION]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[AVION]

	IF OBJECT_ID('[GDD2020].[RUTA_AEREA]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[RUTA_AEREA]

	IF OBJECT_ID('[GDD2020].[VUELO]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[VUELO]

--YO

	IF OBJECT_ID('[GDD2020].[TIPO_HABITACION]', 'U') IS NOT NULL
	DROP TABLE [GDD2020].[TIPO_HABITACION]

	IF OBJECT_ID('[GDD2020].[HABITACION]', 'U') IS NOT NULL
	DROP TABLE [GDD2020].[HABITACION]

	IF OBJECT_ID('[GDD2020].[HOTEL]', 'U') IS NOT NULL
	DROP TABLE [GDD2020].[HOTEL]

	IF OBJECT_ID('[GDD2020].[COMPRA_ESTADIA]', 'U') IS NOT NULL
	DROP TABLE [GDD2020].[COMPRA_ESTADIA]

	IF OBJECT_ID('[GDD2020].[ESTADIA_X_DIA]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[ESTADIA_X_DIA]

	IF OBJECT_ID('[GDD2020].[VENTA_ESTADIA]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[VENTA_ESTADIA]

	IF OBJECT_ID('[GDD2020].[FACTURA]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[FACTURA]

	IF OBJECT_ID('[GDD2020].[COMPRA]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[COMPRA]

	IF OBJECT_ID('[GDD2020].[PASAJE]', 'U') IS NOT NULL 
	DROP TABLE [GDD2020].[PASAJE]

--BORRANDO ESQUEMA
	EXEC('DROP SCHEMA GDD2020');
	PRINT('Schema GDD2020 eliminado!')
END

--CREANDO NUEVO ESQUEMA
PRINT('Creando el Schema GDD2020...')
EXEC('CREATE SCHEMA GDD2020 AUTHORIZATION dbo');
GO

--CREANDO NUEVAS TABLAS

PRINT('Creando tablas...')

CREATE TABLE [GDD2020].[SUCURSALES](
	[SUCURSAL_CODIGO] BIGINT IDENTITY(1,1) PRIMARY KEY,
	[SUCURSAL_DIRECCION] [nvarchar](255) NOT NULL,
	[SUCURSAL_MAIL] [nvarchar](255) NOT NULL,
	[SUCURSAL_TELEFONO] [decimal](18, 0) NOT  NULL
)ON [PRIMARY]

CREATE TABLE [GDD2020].[USUARIO](
	[USUARIO_USERNAME] [nvarchar](20) NOT NULL PRIMARY KEY,
	[USUARIO_PASSWORD] BINARY(256) NOT NULL,
	[USUARIO_HABILITADO] BIT NOT NULL,
--	[USUARIO_RXU_CODIGO] BIGINT NOT NULL,
--	CONSTRAINT FK_USUARIO_RXU_CODIGO FOREIGN KEY([USUARIO_RXU_CODIGO]) REFERENCES [GDD2020].[ROLXUSUARIO](RXU_CODIGO)
)ON [PRIMARY]

CREATE TABLE [GDD2020].[ROL](
	ROL_CODIGO BIGINT IDENTITY(1,1) PRIMARY KEY,
	ROL_NOMBRE [nvarchar](255) NOT NULL UNIQUE,
	ROL_ACTIVO BIT NOT NULL
)ON [PRIMARY]

CREATE TABLE [GDD2020].[FUNCIONALIDAD](
	FUNCIONALIDAD_CODIGO BIGINT IDENTITY(1,1) PRIMARY KEY,
	FUNCIONALIDAD_NOMBRE [nvarchar](255) NOT NULL UNIQUE
) ON [PRIMARY]

CREATE TABLE [GDD2020].[ROLXUSUARIO](
	RXU_CODIGO BIGINT IDENTITY(1,1) PRIMARY KEY,
	RXU_ROL_CODIGO BIGINT NOT NULL,
	RXU_USUARIO_USERNAME [nvarchar](20) NOT NULL,
	CONSTRAINT UC_ROLXUSUARIO UNIQUE(RXU_ROL_CODIGO, RXU_USUARIO_USERNAME),
	CONSTRAINT FK_RXU_ROL_CODIGO FOREIGN KEY(RXU_ROL_CODIGO) REFERENCES [GDD2020].[ROL]([ROL_CODIGO]),
	CONSTRAINT FK_RXU_USUARIO_USERNAME FOREIGN KEY(RXU_USUARIO_USERNAME) REFERENCES [GDD2020].[USUARIO]([USUARIO_USERNAME])
) ON [PRIMARY]

CREATE TABLE [GDD2020].[FUNCIONALIDADXROL](
	RXF_CODIGO BIGINT IDENTITY(1,1) PRIMARY KEY,
	RXF_ROL_CODIGO BIGINT NOT NULL,
	RXF_FUNC_CODIGO BIGINT NOT NULL,
	CONSTRAINT UC_ROL_X_FUNCIONALIDAD UNIQUE(RXF_ROL_CODIGO, RXF_FUNC_CODIGO),
	CONSTRAINT FK_RXF_ROL_CODIGO FOREIGN KEY(RXF_ROL_CODIGO) REFERENCES [GDD2020].[ROL]([ROL_CODIGO]),
	CONSTRAINT FK_RXF_FUNC_CODIGO FOREIGN KEY(RXF_FUNC_CODIGO) REFERENCES [GDD2020].[FUNCIONALIDAD]([FUNCIONALIDAD_CODIGO])
) ON [PRIMARY]


CREATE TABLE [GDD2020].[CLIENTE](
	[CLIENTE_NUMERO] BIGINT IDENTITY(1,1) PRIMARY KEY,
	[CLIENTE_APELLIDO] [nvarchar](255)  NOT NULL,
	[CLIENTE_NOMBRE] [nvarchar](255)  NOT NULL,
	[CLIENTE_DNI] [decimal](18,0) NOT NULL,
	[CLIENTE_FECHA_NAC] [datetime2](3) NOT  NULL,
	[CLIENTE_MAIL] [nvarchar](255) NOT NULL,
	[CLIENTE_TELEFONO] [int] NOT NULL,
	[CLIENTE_USUARIO_USERNAME] [nvarchar](20) NOT NULL,
	CONSTRAINT FK_CLIENTE_USUARIO_USERNAME FOREIGN KEY([CLIENTE_USUARIO_USERNAME]) REFERENCES [GDD2020].[USUARIO]([USUARIO_USERNAME])
)ON [PRIMARY]



CREATE TABLE [GDD2020].[PROVEEDOR](
	[PROVEEDOR_CODIGO] BIGINT IDENTITY(1,1) PRIMARY KEY,
	[EMPRESA_RAZON_SOCIAL] [nvarchar](255) NOT NULL,
)ON [PRIMARY]


CREATE TABLE [GDD2020].[TIPO_BUTACA](
	TIPO_BUTACA_CODIGO BIGINT IDENTITY(1,1) PRIMARY KEY,
	TIPO_BUTACA_DESCRIPCION [nvarchar](255) NOT NULL,
)ON [PRIMARY]

CREATE TABLE [GDD2020].[BUTACA](
	BUTACA_NUMERO decimal(18,0)  NOT NULL PRIMARY KEY,
	BUTACA_TIPO [nvarchar](255) NOT NULL,
)ON [PRIMARY]

CREATE TABLE [GDD2020].[AVION](
	AVION_IDENTIFICADOR [nvarchar](50) NOT NULL PRIMARY KEY,
	AVION_MODELO[nvarchar](50),
	AVION_BUTACA_NUMERO decimal (18,0) NOT NULL, 
	CONSTRAINT FK_AVION_BUTACA_NUMERO FOREIGN KEY (AVION_BUTACA_NUMERO) REFERENCES [GDD2020].[BUTACA](BUTACA_NUMERO)
)ON [PRIMARY]

CREATE TABLE [GDD2020].[RUTA_AEREA](
	RUTA_AEREA_CODIGO BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	RUTA_AEREA_CIU_ORIG [nvarchar](255) NOT NULL,
	RUTA_AEREA_CIU_DEST [nvarchar](255) NOT NULL,
)ON [PRIMARY]


CREATE TABLE [GDD2020].[VUELO](
	VUELO_CODIGO BIGINT IDENTITY(1,1) PRIMARY KEY,
	VUELO_FECHA_SALIDA [datetime2](7) NOT NULL,
	VUELO_FECHA_LLEGADA [datetime2](7)  NOT NULL,
	VUELO_RUTA_AEREA_CODIGO BIGINT NOT NULL, 
	VUELO_AVION_IDENTIFICADOR  [nvarchar](50) NOT NULL,
	CONSTRAINT FK_VUELO_AVION_IDENTIFICADOR  FOREIGN KEY (VUELO_AVION_IDENTIFICADOR) REFERENCES [GDD2020].[AVION](AVION_IDENTIFICADOR),
	CONSTRAINT FK_VUELO_RUTA_AEREA_CODIGO FOREIGN KEY (VUELO_RUTA_AEREA_CODIGO) REFERENCES [GDD2020].[RUTA_AEREA](RUTA_AEREA_CODIGO)
)ON [PRIMARY]

--yo

CREATE TABLE [GDD2020].[TIPO_HABITACION](
	TIPO_HABITACION_CODIGO BIGINT IDENTITY(1,1)PRIMARY KEY,
	TIPO_HABITACION_DESC [nvarchar](50) NOT NULL
	)ON [PRIMARY]

CREATE TABLE [GDD2020].[HABITACION](
	HABITACION_NUMERO BIGINT IDENTITY(1,1) PRIMARY KEY,
	HABITACION_PISO BIGINT NOT NULL,
	HABITACION_FRENTE BIGINT NOT NULL,
	HABITACION_COSTO BIGINT NOT NULL,
	HABITACION_PRECIO BIGINT NOT NULL,
	TIPO_HABITACION_CODIGO BIGINT NOT NULL,
	CONSTRAINT FK_TIPO_HABITACION_CODIGO FOREIGN KEY (TIPO_HABITACION_CODIGO) REFERENCES [GDD2020].[TIPO_HABITACION](TIPO_HABITACION_CODIGO)
	)ON [PRIMARY]

CREATE TABLE [GDD2020].[HOTEL](
    HOTEL_CODIGO BIGINT IDENTITY(1,1) PRIMARY KEY,
	HOTEL_CALLE [nvarchar](50) NOT NULL,
	HOTEL_NRO_CALLE BIGINT NOT NULL,
	HOTEL_CANTIDAD_ESTRELLAS BIGINT NOT NULL,
	HABITACION_NUMERO BIGINT NOT NULL,
	CONSTRAINT FK_HABITACION_NUMERO  FOREIGN KEY (HABITACION_NUMERO) REFERENCES [GDD2020].[HABITACION](HABITACION_NUMERO)
	)ON [PRIMARY]

CREATE TABLE [GDD2020].[COMPRA_ESTADIA](
	ESTADIA_CODIGO BIGINT IDENTITY(1,1) PRIMARY KEY,
	ESTADIA_FECHA_INICIO [datetime2](7) NOT NULL,
	ESTADIA_CANTIDAD_NOCHES BIGINT NOT NULL,
	ESTADIA_PRECIO_COSTO BIGINT NOT NULL,
	HOTEL_CODIGO BIGINT NOT NULL,
	CONSTRAINT FK_HOTEL_CODIGO  FOREIGN KEY (HOTEL_CODIGO) REFERENCES [GDD2020].[HOTEL](HOTEL_CODIGO)
	)ON [PRIMARY]


CREATE TABLE [GDD2020].[PASAJE](
	PASAJE_CODIGO BIGINT IDENTITY(1,1) PRIMARY KEY,
	PASAJE_COSTO BIGINT NOT NULL,
	PASAJE_PRECIO BIGINT NOT NULL,
	PASAJE_FECHA_COMPRA [datetime2](7),
	VUELO_CODIGO BIGINT NOT NULL,
	CONSTRAINT FK_VUELO_CODIGO FOREIGN KEY (VUELO_CODIGO) REFERENCES [GDD2020].[VUELO](VUELO_CODIGO)
	)ON [PRIMARY]

CREATE TABLE [GDD2020].[COMPRA](
	COMPRA_NUMERO BIGINT IDENTITY(1,1) PRIMARY KEY,	
	PASAJE_CODIGO BIGINT NOT NULL,
	COMPRA_FECHA [datetime2](7),
	PROVEEDOR_CODIGO BIGINT NOT NULL,
	ESTADIA_CODIGO BIGINT NOT NULL,
	USUARIO_USERNAME [nvarchar](20) NOT NULL,
	CONSTRAINT FK_PASAJE_CODIGO FOREIGN KEY (PASAJE_CODIGO) REFERENCES [GDD2020].[PASAJE](PASAJE_CODIGO),
	CONSTRAINT FK_PROVEEDOR_CODIGO FOREIGN KEY (PROVEEDOR_CODIGO) REFERENCES [GDD2020].[PROVEEDOR](PROVEEDOR_CODIGO),
	CONSTRAINT FK_ESTADIA_CODIGO FOREIGN KEY (ESTADIA_CODIGO) REFERENCES [GDD2020].[COMPRA_ESTADIA](ESTADIA_CODIGO),
	CONSTRAINT FK_USUARIO_USERNAME FOREIGN KEY (USUARIO_USERNAME) REFERENCES [GDD2020].[USUARIO](USUARIO_USERNAME)
	)ON [PRIMARY]

CREATE TABLE [GDD2020].[FACTURA](
	FACTURA_FECHA [datetime2](7),
	FACTURA_NRO BIGINT IDENTITY(1,1) PRIMARY KEY,
	NUMERO_CLIENTE BIGINT NOT NULL,---ESTA RARO , NO ESTA DECLARADO COMO EN EL DER PERO IGUAL LE HICE REFERENCIA AL CAMPO
	SUCURSAL_CODIGO BIGINT NOT NULL,
	COMPRA_NUMERO BIGINT NOT NULL,
	IMPORTE BIGINT NOT NULL,
	
	CONSTRAINT FK_NUMERO_CLIENTE FOREIGN KEY (NUMERO_CLIENTE) REFERENCES [GDD2020].[CLIENTE](CLIENTE_NUMERO),
	CONSTRAINT FK_SUCURSAL_CODIGO FOREIGN KEY (SUCURSAL_CODIGO) REFERENCES [GDD2020].[SUCURSALES](SUCURSAL_CODIGO),
	CONSTRAINT FK_COMPRA_NUMERO FOREIGN KEY (COMPRA_NUMERO) REFERENCES [GDD2020].[COMPRA](COMPRA_NUMERO)
	)ON [PRIMARY]


CREATE TABLE [GDD2020].[ESTADIA_X_DIA](
	FECHA [datetime2](7),--CLAVE COMPUESTA TAMBIEN ES PRIMARY KEY
	--ESTADIA_CODIGO BIGINT IDENTITY(1,1) PRIMARY KEY,
	ESTADIA_CODIGO BIGINT NOT NULL,

	PRIMARY KEY(FECHA,ESTADIA_CODIGO),

	FACTURA_NRO BIGINT NOT NULL,
	CONSTRAINT FK_FACTURA_NRO FOREIGN KEY (FACTURA_NRO) REFERENCES [GDD2020].[FACTURA](FACTURA_NRO)
	)ON [PRIMARY]

CREATE TABLE [GDD2020].[VENTA_ESTADIA](
	
	FACTURA_NRO BIGINT NOT NULL,

	FECHA [datetime2](7),
	ESTADIA_CODIGO BIGINT NOT NULL,
	
	VENTA_ESTADIA_CANTIDAD_NOCHES BIGINT NOT NULL,
	VENTA_ESTADIA_FECHA_CHECK_IN [datetime2](7),
	ESTADIA_PRECIO_VENTA BIGINT NOT NULL,
	CONSTRAINT FK_FACTURA_NRO FOREIGN KEY (FACTURA_NRO) REFERENCES [GDD2020].[FACTURA](FACTURA_NRO),
	CONSTRAINT FK_FECHA_ESTADIA_CODIGO FOREIGN KEY (FECHA,ESTADIA_CODIGO) REFERENCES [GDD2020].[ESTADIA_X_DIA](FECHA,ESTADIA_CODIGO)
	)ON [PRIMARY]

--MIGRANDO DATOS
